version: '3.8'

services:
  db:
    image: postgres
    container_name: postgres
    restart: always
    ports:
      - '5432:5432'
    environment:
      POSTGRES_PASSWORD: password1234

  redis:
    image: redis
    container_name: redis
    restart: always
    ports:
      - '6379:6379'
